name: deploy-beam
on: [push]
env:
    BEAM_CLIENT_ID: ${{ secrets.BEAM_CLIENT_ID }}
    BEAM_CLIENT_SECRET: ${{ secrets.BEAM_CLIENT_SECRET }}
    PROFILE: ${{ secrets.BEAM_PROFILE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Authenticate"
        run: |
          curl https://raw.githubusercontent.com/slai-labs/get-beam/main/get-beam.sh -sSfL | sh
          pip3 install --upgrade pip
          pip3 install beam-sdk
          beam configure --clientId=$BEAM_CLIENT_ID --clientSecret=$BEAM_CLIENT_SECRET
      - uses: actions/checkout@v3
      - name: "Serve"
        # Replace app.py with the path to your Beam entry point
        run: |
          {
            echo 'PREVIEW_URL<<EOF' 
            beam serve app.py
            echo EOF
          } >> "$GITHUB_ENV"

          stopMarker=$(uuidgen)
          echo "::stop-commands::$stopMarker"
      - name: "Generate URL"
        run: |
          echo "$PREVIEW_URL"